spring:
  datasource:
    url: jdbc:postgresql://psqlserver/bank-api-liquibase
    username: admin
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect