spring:
  datasource:
    url: jdbc:mysql://mysqlserver/bank-api-liquibase?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect