version: '3.3'
services:
  bank-api-latest:
    build:
      context: ..
      dockerfile: Standalone # Image to build and run source files
#      dockerfile: Dockerfile # Image to run build files
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker-psql
#      - SPRING_PROFILES_ACTIVE=docker-mysql
    image: asimx/bank-api-latest
    depends_on:
      - psqlserver
#      - mysqlserver

  psqlserver:
    container_name: psqlserver
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bank-api-liquibase
    ports:
      - '5432:5432'
    image: 'postgres:13.1-alpine'

#  mysql:
#    container_name: mysqlserver
#    environment:
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=pass
#      - MYSQL_ROOT_PASSWORD=pass
#      - MYSQL_DATABASE=bank-api-liquibase
#    ports:
#      - '3306:3306'
#    image: 'mysql:8.0'